### ISSUE TITLE
What is the training equipment used?

### ISSUE THREAD

**Issue by lxysl** [mako443/text-to-pointcloud#9]
I am impressed by your outstanding work! Could you please provide me with some information about the training process? Specifically, what GPUs did you use and how many were used during training? Additionally, could you tell me how much memory was required for training? Thank you in advance.

**Comment by mako443** [comment]
Hi, thank you for your comment and please excuse the late reply!
The training was performed on single GPUs that had either 16 or 32GB of memory, V100 if I remember correctly. 16GB was enough for most experiments, only some ablations with large batch sizes / models, or denser point clouds needed more.

**Comment by lxysl** [comment]
Thanks for the response! Helps a lot!
